# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _person
else:
    import _person

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _person.delete_SwigPyIterator

    def value(self):
        return _person.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _person.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _person.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _person.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _person.SwigPyIterator_equal(self, x)

    def copy(self):
        return _person.SwigPyIterator_copy(self)

    def next(self):
        return _person.SwigPyIterator_next(self)

    def __next__(self):
        return _person.SwigPyIterator___next__(self)

    def previous(self):
        return _person.SwigPyIterator_previous(self)

    def advance(self, n):
        return _person.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _person.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _person.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _person.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _person.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _person.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _person.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _person:
_person.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _person.SHARED_PTR_DISOWN
class PersonVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _person.PersonVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _person.PersonVector___nonzero__(self)

    def __bool__(self):
        return _person.PersonVector___bool__(self)

    def __len__(self):
        return _person.PersonVector___len__(self)

    def __getslice__(self, i, j):
        return _person.PersonVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _person.PersonVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _person.PersonVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _person.PersonVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _person.PersonVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _person.PersonVector___setitem__(self, *args)

    def pop(self):
        return _person.PersonVector_pop(self)

    def append(self, x):
        return _person.PersonVector_append(self, x)

    def empty(self):
        return _person.PersonVector_empty(self)

    def size(self):
        return _person.PersonVector_size(self)

    def swap(self, v):
        return _person.PersonVector_swap(self, v)

    def begin(self):
        return _person.PersonVector_begin(self)

    def end(self):
        return _person.PersonVector_end(self)

    def rbegin(self):
        return _person.PersonVector_rbegin(self)

    def rend(self):
        return _person.PersonVector_rend(self)

    def clear(self):
        return _person.PersonVector_clear(self)

    def get_allocator(self):
        return _person.PersonVector_get_allocator(self)

    def pop_back(self):
        return _person.PersonVector_pop_back(self)

    def erase(self, *args):
        return _person.PersonVector_erase(self, *args)

    def __init__(self, *args):
        _person.PersonVector_swiginit(self, _person.new_PersonVector(*args))

    def push_back(self, x):
        return _person.PersonVector_push_back(self, x)

    def front(self):
        return _person.PersonVector_front(self)

    def back(self):
        return _person.PersonVector_back(self)

    def assign(self, n, x):
        return _person.PersonVector_assign(self, n, x)

    def resize(self, *args):
        return _person.PersonVector_resize(self, *args)

    def insert(self, *args):
        return _person.PersonVector_insert(self, *args)

    def reserve(self, n):
        return _person.PersonVector_reserve(self, n)

    def capacity(self):
        return _person.PersonVector_capacity(self)
    __swig_destroy__ = _person.delete_PersonVector

# Register PersonVector in _person:
_person.PersonVector_swigregister(PersonVector)
class Person(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_person.Person_name_get, _person.Person_name_set)
    age = property(_person.Person_age_get, _person.Person_age_set)

    def __init__(self):
        _person.Person_swiginit(self, _person.new_Person())
    __swig_destroy__ = _person.delete_Person

# Register Person in _person:
_person.Person_swigregister(Person)

def displayv1(persons):
    return _person.displayv1(persons)

def displayv2(persons):
    return _person.displayv2(persons)

